CREATE TABLE "students" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_number" varchar(50) UNIQUE,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "email" varchar(150) UNIQUE,
  "phone" varchar(30),
  "department_id" bigint,
  "enrollment_year" int,
  "created_at" timestamp
);

CREATE TABLE "departments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE,
  "name" varchar(150),
  "created_at" timestamp
);

CREATE TABLE "staff_users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE,
  "email" varchar(150) UNIQUE,
  "full_name" varchar(150),
  "department_id" bigint,
  "role_id" bigint,
  "password_hash" text,
  "created_at" timestamp
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE
);

CREATE TABLE "clearance_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "start_date" date,
  "end_date" date,
  "active" boolean,
  "created_at" timestamp
);

CREATE TABLE "clearance_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE,
  "title" varchar(200),
  "description" text,
  "department_id" bigint,
  "approver_staff_id" bigint,
  "requires_attachment" boolean,
  "sequence" int,
  "created_at" timestamp
);

CREATE TABLE "clearance_records" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "clearance_item_id" bigint,
  "session_id" bigint,
  "status" varchar(30),
  "note" text,
  "handled_by" bigint,
  "handled_at" timestamp,
  "attachment_url" text,
  "updated_at" timestamp
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient_user_id" bigint,
  "recipient_student_id" bigint,
  "message" text,
  "read" boolean,
  "created_at" timestamp
);

ALTER TABLE "students" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "staff_users" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "staff_users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "clearance_items" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");

ALTER TABLE "clearance_items" ADD FOREIGN KEY ("approver_staff_id") REFERENCES "staff_users" ("id");

ALTER TABLE "clearance_records" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "clearance_records" ADD FOREIGN KEY ("clearance_item_id") REFERENCES "clearance_items" ("id");

ALTER TABLE "clearance_records" ADD FOREIGN KEY ("session_id") REFERENCES "clearance_sessions" ("id");

ALTER TABLE "clearance_records" ADD FOREIGN KEY ("handled_by") REFERENCES "staff_users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_user_id") REFERENCES "staff_users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_student_id") REFERENCES "students" ("id");
