-- ============================
--     STUDENTS
-- ============================
CREATE TABLE students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_number VARCHAR(50) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL,
  department_id BIGINT NOT NULL,
  enrollment_year INT NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     DEPARTMENTS
-- ============================
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     STAFF USERS
-- ============================
CREATE TABLE staff_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(150) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  department_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     ROLES
-- ============================
CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

-- ============================
--     CLEARANCE SESSIONS
-- ============================
CREATE TABLE clearance_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     CLEARANCE ITEMS
-- ============================
CREATE TABLE clearance_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  department_id BIGINT NOT NULL,
  approver_staff_id BIGINT NOT NULL,
  requires_attachment BOOLEAN NOT NULL DEFAULT FALSE,
  sequence INT NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     CLEARANCE RECORDS
-- ============================
CREATE TABLE clearance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  clearance_item_id BIGINT NOT NULL,
  session_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL,
  note TEXT NOT NULL,
  handled_by BIGINT NOT NULL,
  handled_at TIMESTAMP NOT NULL DEFAULT NOW(),
  attachment_url TEXT NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     NOTIFICATIONS
-- ============================
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id BIGINT NOT NULL,
  recipient_student_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ============================
--     FOREIGN KEYS
-- ============================
ALTER TABLE students
  ADD FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE staff_users
  ADD FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE staff_users
  ADD FOREIGN KEY (role_id) REFERENCES roles(id);

ALTER TABLE clearance_items
  ADD FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE clearance_items
  ADD FOREIGN KEY (approver_staff_id) REFERENCES staff_users(id);

ALTER TABLE clearance_records
  ADD FOREIGN KEY (student_id) REFERENCES students(id);

ALTER TABLE clearance_records
  ADD FOREIGN KEY (clearance_item_id) REFERENCES clearance_items(id);

ALTER TABLE clearance_records
  ADD FOREIGN KEY (session_id) REFERENCES clearance_sessions(id);

ALTER TABLE clearance_records
  ADD FOREIGN KEY (handled_by) REFERENCES staff_users(id);

ALTER TABLE notifications
  ADD FOREIGN KEY (recipient_user_id) REFERENCES staff_users(id);

ALTER TABLE notifications
  ADD FOREIGN KEY (recipient_student_id) REFERENCES students(id);
