DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS clearance_records CASCADE;
DROP TABLE IF EXISTS clearance_items CASCADE;
DROP TABLE IF EXISTS clearance_sessions CASCADE;
DROP TABLE IF EXISTS staff_users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

