// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clearance_items.sql

package db

import (
	"context"
	"database/sql"
)

const createClearanceItem = `-- name: CreateClearanceItem :one
INSERT INTO clearance_items (
    code, title, description, department_id,
    approver_staff_id, requires_attachment,
    sequence, created_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,NOW())
RETURNING id, code, title, description, department_id, approver_staff_id, requires_attachment, sequence, created_at
`

type CreateClearanceItemParams struct {
	Code               sql.NullString `json:"code"`
	Title              sql.NullString `json:"title"`
	Description        sql.NullString `json:"description"`
	DepartmentID       sql.NullInt64  `json:"department_id"`
	ApproverStaffID    sql.NullInt64  `json:"approver_staff_id"`
	RequiresAttachment sql.NullBool   `json:"requires_attachment"`
	Sequence           sql.NullInt32  `json:"sequence"`
}

func (q *Queries) CreateClearanceItem(ctx context.Context, arg CreateClearanceItemParams) (ClearanceItem, error) {
	row := q.db.QueryRowContext(ctx, createClearanceItem,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.DepartmentID,
		arg.ApproverStaffID,
		arg.RequiresAttachment,
		arg.Sequence,
	)
	var i ClearanceItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DepartmentID,
		&i.ApproverStaffID,
		&i.RequiresAttachment,
		&i.Sequence,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClearanceItem = `-- name: DeleteClearanceItem :exec
DELETE FROM clearance_items WHERE id = $1
`

func (q *Queries) DeleteClearanceItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClearanceItem, id)
	return err
}

const getClearanceItem = `-- name: GetClearanceItem :one
SELECT id, code, title, description, department_id, approver_staff_id, requires_attachment, sequence, created_at FROM clearance_items WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClearanceItem(ctx context.Context, id int64) (ClearanceItem, error) {
	row := q.db.QueryRowContext(ctx, getClearanceItem, id)
	var i ClearanceItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DepartmentID,
		&i.ApproverStaffID,
		&i.RequiresAttachment,
		&i.Sequence,
		&i.CreatedAt,
	)
	return i, err
}

const listClearanceItems = `-- name: ListClearanceItems :many
SELECT id, code, title, description, department_id, approver_staff_id, requires_attachment, sequence, created_at FROM clearance_items ORDER BY sequence
`

func (q *Queries) ListClearanceItems(ctx context.Context) ([]ClearanceItem, error) {
	rows, err := q.db.QueryContext(ctx, listClearanceItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceItem{}
	for rows.Next() {
		var i ClearanceItem
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.DepartmentID,
			&i.ApproverStaffID,
			&i.RequiresAttachment,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByDepartment = `-- name: ListItemsByDepartment :many
SELECT id, code, title, description, department_id, approver_staff_id, requires_attachment, sequence, created_at FROM clearance_items WHERE department_id = $1 ORDER BY sequence
`

func (q *Queries) ListItemsByDepartment(ctx context.Context, departmentID sql.NullInt64) ([]ClearanceItem, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceItem{}
	for rows.Next() {
		var i ClearanceItem
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.DepartmentID,
			&i.ApproverStaffID,
			&i.RequiresAttachment,
			&i.Sequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClearanceItem = `-- name: UpdateClearanceItem :one
UPDATE clearance_items SET
    code = $1,
    title = $2,
    description = $3,
    department_id = $4,
    approver_staff_id = $5,
    requires_attachment = $6,
    sequence = $7
WHERE id = $8 RETURNING id, code, title, description, department_id, approver_staff_id, requires_attachment, sequence, created_at
`

type UpdateClearanceItemParams struct {
	Code               sql.NullString `json:"code"`
	Title              sql.NullString `json:"title"`
	Description        sql.NullString `json:"description"`
	DepartmentID       sql.NullInt64  `json:"department_id"`
	ApproverStaffID    sql.NullInt64  `json:"approver_staff_id"`
	RequiresAttachment sql.NullBool   `json:"requires_attachment"`
	Sequence           sql.NullInt32  `json:"sequence"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateClearanceItem(ctx context.Context, arg UpdateClearanceItemParams) (ClearanceItem, error) {
	row := q.db.QueryRowContext(ctx, updateClearanceItem,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.DepartmentID,
		arg.ApproverStaffID,
		arg.RequiresAttachment,
		arg.Sequence,
		arg.ID,
	)
	var i ClearanceItem
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.DepartmentID,
		&i.ApproverStaffID,
		&i.RequiresAttachment,
		&i.Sequence,
		&i.CreatedAt,
	)
	return i, err
}
