// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clearance_requests.sql

package db

import (
	"context"
)

const createClearanceRequest = `-- name: CreateClearanceRequest :one
INSERT INTO clearance_requests (
    student_id, session_id
) VALUES ($1, $2)
RETURNING id, student_id, session_id, status, created_at
`

type CreateClearanceRequestParams struct {
	StudentID int64 `json:"student_id"`
	SessionID int64 `json:"session_id"`
}

func (q *Queries) CreateClearanceRequest(ctx context.Context, arg CreateClearanceRequestParams) (ClearanceRequest, error) {
	row := q.db.QueryRowContext(ctx, createClearanceRequest, arg.StudentID, arg.SessionID)
	var i ClearanceRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getClearanceRequest = `-- name: GetClearanceRequest :one
SELECT id, student_id, session_id, status, created_at FROM clearance_requests WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClearanceRequest(ctx context.Context, id int64) (ClearanceRequest, error) {
	row := q.db.QueryRowContext(ctx, getClearanceRequest, id)
	var i ClearanceRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentRequestForSession = `-- name: GetStudentRequestForSession :one
SELECT id, student_id, session_id, status, created_at FROM clearance_requests
WHERE student_id = $1 AND session_id = $2
LIMIT 1
`

type GetStudentRequestForSessionParams struct {
	StudentID int64 `json:"student_id"`
	SessionID int64 `json:"session_id"`
}

func (q *Queries) GetStudentRequestForSession(ctx context.Context, arg GetStudentRequestForSessionParams) (ClearanceRequest, error) {
	row := q.db.QueryRowContext(ctx, getStudentRequestForSession, arg.StudentID, arg.SessionID)
	var i ClearanceRequest
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRequests = `-- name: ListAllRequests :many
SELECT id, student_id, session_id, status, created_at FROM clearance_requests
ORDER BY created_at DESC
`

func (q *Queries) ListAllRequests(ctx context.Context) ([]ClearanceRequest, error) {
	rows, err := q.db.QueryContext(ctx, listAllRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceRequest{}
	for rows.Next() {
		var i ClearanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByStudent = `-- name: ListRequestsByStudent :many
SELECT id, student_id, session_id, status, created_at FROM clearance_requests
WHERE student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRequestsByStudent(ctx context.Context, studentID int64) ([]ClearanceRequest, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceRequest{}
	for rows.Next() {
		var i ClearanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClearanceRequestStatus = `-- name: UpdateClearanceRequestStatus :exec
UPDATE clearance_requests
SET status = $1
WHERE id = $2
`

type UpdateClearanceRequestStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateClearanceRequestStatus(ctx context.Context, arg UpdateClearanceRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateClearanceRequestStatus, arg.Status, arg.ID)
	return err
}
