// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clearance_sessions.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO clearance_sessions (
    name, start_date, end_date, active, created_at
) VALUES ($1,$2,$3,$4,NOW())
RETURNING id, name, start_date, end_date, active, created_at
`

type CreateSessionParams struct {
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Active    bool      `json:"active"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ClearanceSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Active,
	)
	var i ClearanceSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM clearance_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, name, start_date, end_date, active, created_at FROM clearance_sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int64) (ClearanceSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i ClearanceSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, name, start_date, end_date, active, created_at FROM clearance_sessions ORDER BY id
`

func (q *Queries) ListSessions(ctx context.Context) ([]ClearanceSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceSession{}
	for rows.Next() {
		var i ClearanceSession
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE clearance_sessions SET
    name = $1,
    start_date = $2,
    end_date = $3,
    active = $4
WHERE id = $5
RETURNING id, name, start_date, end_date, active, created_at
`

type UpdateSessionParams struct {
	Name      string    `json:"name"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Active    bool      `json:"active"`
	ID        int64     `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (ClearanceSession, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.Active,
		arg.ID,
	)
	var i ClearanceSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
