// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clearance_records.sql

package db

import (
	"context"
	"time"
)

const createClearanceRecord = `-- name: CreateClearanceRecord :one
INSERT INTO clearance_records (
    student_id, clearance_item_id, session_id,
    status, note, handled_by, attachment_url, updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,NOW())
RETURNING id, student_id, clearance_item_id, session_id, status, note, handled_by, handled_at, attachment_url, updated_at
`

type CreateClearanceRecordParams struct {
	StudentID       int64  `json:"student_id"`
	ClearanceItemID int64  `json:"clearance_item_id"`
	SessionID       int64  `json:"session_id"`
	Status          string `json:"status"`
	Note            string `json:"note"`
	HandledBy       int64  `json:"handled_by"`
	AttachmentUrl   string `json:"attachment_url"`
}

func (q *Queries) CreateClearanceRecord(ctx context.Context, arg CreateClearanceRecordParams) (ClearanceRecord, error) {
	row := q.db.QueryRowContext(ctx, createClearanceRecord,
		arg.StudentID,
		arg.ClearanceItemID,
		arg.SessionID,
		arg.Status,
		arg.Note,
		arg.HandledBy,
		arg.AttachmentUrl,
	)
	var i ClearanceRecord
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ClearanceItemID,
		&i.SessionID,
		&i.Status,
		&i.Note,
		&i.HandledBy,
		&i.HandledAt,
		&i.AttachmentUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClearanceRecord = `-- name: DeleteClearanceRecord :exec
DELETE FROM clearance_records WHERE id = $1
`

func (q *Queries) DeleteClearanceRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClearanceRecord, id)
	return err
}

const getClearanceRecord = `-- name: GetClearanceRecord :one
SELECT id, student_id, clearance_item_id, session_id, status, note, handled_by, handled_at, attachment_url, updated_at FROM clearance_records WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClearanceRecord(ctx context.Context, id int64) (ClearanceRecord, error) {
	row := q.db.QueryRowContext(ctx, getClearanceRecord, id)
	var i ClearanceRecord
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ClearanceItemID,
		&i.SessionID,
		&i.Status,
		&i.Note,
		&i.HandledBy,
		&i.HandledAt,
		&i.AttachmentUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecordsBySession = `-- name: ListRecordsBySession :many
SELECT id, student_id, clearance_item_id, session_id, status, note, handled_by, handled_at, attachment_url, updated_at FROM clearance_records
WHERE session_id = $1
ORDER BY student_id
`

func (q *Queries) ListRecordsBySession(ctx context.Context, sessionID int64) ([]ClearanceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceRecord{}
	for rows.Next() {
		var i ClearanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ClearanceItemID,
			&i.SessionID,
			&i.Status,
			&i.Note,
			&i.HandledBy,
			&i.HandledAt,
			&i.AttachmentUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsByStudent = `-- name: ListRecordsByStudent :many
SELECT id, student_id, clearance_item_id, session_id, status, note, handled_by, handled_at, attachment_url, updated_at FROM clearance_records
WHERE student_id = $1
ORDER BY clearance_item_id
`

func (q *Queries) ListRecordsByStudent(ctx context.Context, studentID int64) ([]ClearanceRecord, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClearanceRecord{}
	for rows.Next() {
		var i ClearanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ClearanceItemID,
			&i.SessionID,
			&i.Status,
			&i.Note,
			&i.HandledBy,
			&i.HandledAt,
			&i.AttachmentUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClearanceRecordStatus = `-- name: UpdateClearanceRecordStatus :one
UPDATE clearance_records SET
    status = $1,
    note = $2,
    handled_by = $3,
    handled_at = $4,
    attachment_url = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, student_id, clearance_item_id, session_id, status, note, handled_by, handled_at, attachment_url, updated_at
`

type UpdateClearanceRecordStatusParams struct {
	Status        string    `json:"status"`
	Note          string    `json:"note"`
	HandledBy     int64     `json:"handled_by"`
	HandledAt     time.Time `json:"handled_at"`
	AttachmentUrl string    `json:"attachment_url"`
	ID            int64     `json:"id"`
}

func (q *Queries) UpdateClearanceRecordStatus(ctx context.Context, arg UpdateClearanceRecordStatusParams) (ClearanceRecord, error) {
	row := q.db.QueryRowContext(ctx, updateClearanceRecordStatus,
		arg.Status,
		arg.Note,
		arg.HandledBy,
		arg.HandledAt,
		arg.AttachmentUrl,
		arg.ID,
	)
	var i ClearanceRecord
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ClearanceItemID,
		&i.SessionID,
		&i.Status,
		&i.Note,
		&i.HandledBy,
		&i.HandledAt,
		&i.AttachmentUrl,
		&i.UpdatedAt,
	)
	return i, err
}
