// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package db

import (
	"context"
	"database/sql"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    code, name, created_at
) VALUES ($1,$2,NOW())
RETURNING id, code, name, created_at
`

type CreateDepartmentParams struct {
	Code sql.NullString `json:"code"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment, arg.Code, arg.Name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDepartment, id)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, code, name, created_at FROM departments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id int64) (Department, error) {
	row := q.db.QueryRowContext(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDepartmentByCode = `-- name: GetDepartmentByCode :one
SELECT id, code, name, created_at FROM departments WHERE code = $1 LIMIT 1
`

func (q *Queries) GetDepartmentByCode(ctx context.Context, code sql.NullString) (Department, error) {
	row := q.db.QueryRowContext(ctx, getDepartmentByCode, code)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, code, name, created_at FROM departments ORDER BY id
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments SET
    code = $1,
    name = $2
WHERE id = $3 RETURNING id, code, name, created_at
`

type UpdateDepartmentParams struct {
	Code sql.NullString `json:"code"`
	Name sql.NullString `json:"name"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, updateDepartment, arg.Code, arg.Name, arg.ID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
