// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    recipient_user_id, recipient_student_id,
    message, read, created_at
) VALUES ($1,$2,$3,$4,NOW())
RETURNING id, recipient_user_id, recipient_student_id, message, read, created_at
`

type CreateNotificationParams struct {
	RecipientUserID    sql.NullInt64 `json:"recipient_user_id"`
	RecipientStudentID sql.NullInt64 `json:"recipient_student_id"`
	Message            string        `json:"message"`
	Read               bool          `json:"read"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.RecipientUserID,
		arg.RecipientStudentID,
		arg.Message,
		arg.Read,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.RecipientStudentID,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_user_id, recipient_student_id, message, read, created_at FROM notifications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.RecipientStudentID,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForStudent = `-- name: ListNotificationsForStudent :many
SELECT id, recipient_user_id, recipient_student_id, message, read, created_at
FROM notifications
WHERE recipient_student_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsForStudent(ctx context.Context, recipientStudentID sql.NullInt64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForStudent, recipientStudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientUserID,
			&i.RecipientStudentID,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, recipient_user_id, recipient_student_id, message, read, created_at
FROM notifications
WHERE recipient_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsForUser(ctx context.Context, recipientUserID sql.NullInt64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUser, recipientUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientUserID,
			&i.RecipientStudentID,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read = TRUE
WHERE id = $1 RETURNING id, recipient_user_id, recipient_student_id, message, read, created_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientUserID,
		&i.RecipientStudentID,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
