// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActivateSession(ctx context.Context, id int64) error
	CreateClearanceItem(ctx context.Context, arg CreateClearanceItemParams) (ClearanceItem, error)
	CreateClearanceRecord(ctx context.Context, arg CreateClearanceRecordParams) (ClearanceRecord, error)
	CreateClearanceRequest(ctx context.Context, arg CreateClearanceRequestParams) (ClearanceRequest, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRole(ctx context.Context, name string) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (ClearanceSession, error)
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	DeactivateAllSessions(ctx context.Context) error
	DeleteClearanceItem(ctx context.Context, id int64) error
	DeleteClearanceRecord(ctx context.Context, id int64) error
	DeleteDepartment(ctx context.Context, id int64) error
	DeleteNotification(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id int64) error
	DeleteStaffUser(ctx context.Context, id int64) error
	DeleteStudent(ctx context.Context, id int64) error
	GetActiveSession(ctx context.Context) (ClearanceSession, error)
	GetClearanceItem(ctx context.Context, id int64) (ClearanceItem, error)
	GetClearanceRecord(ctx context.Context, id int64) (ClearanceRecord, error)
	GetClearanceRequest(ctx context.Context, id int64) (ClearanceRequest, error)
	GetDepartment(ctx context.Context, id int64) (Department, error)
	GetDepartmentByCode(ctx context.Context, code string) (Department, error)
	GetNotification(ctx context.Context, id int64) (Notification, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetSession(ctx context.Context, id int64) (ClearanceSession, error)
	GetStaffUser(ctx context.Context, id int64) (StaffUser, error)
	GetStaffUserByEmail(ctx context.Context, email string) (StaffUser, error)
	GetStaffUserByUsername(ctx context.Context, username string) (StaffUser, error)
	GetStudent(ctx context.Context, id int64) (Student, error)
	GetStudentByStudentNumber(ctx context.Context, studentNumber string) (Student, error)
	GetStudentByStudentNumberForUpdate(ctx context.Context, studentNumber string) (Student, error)
	GetStudentForUpdate(ctx context.Context, id int64) (Student, error)
	GetStudentRequestForSession(ctx context.Context, arg GetStudentRequestForSessionParams) (ClearanceRequest, error)
	ListAllRequests(ctx context.Context) ([]ClearanceRequest, error)
	ListClearanceItems(ctx context.Context) ([]ClearanceItem, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListItemsByDepartment(ctx context.Context, departmentID int64) ([]ClearanceItem, error)
	ListNotificationsForStudent(ctx context.Context, recipientStudentID sql.NullInt64) ([]Notification, error)
	ListNotificationsForUser(ctx context.Context, recipientUserID sql.NullInt64) ([]Notification, error)
	ListRecordsBySession(ctx context.Context, sessionID int64) ([]ClearanceRecord, error)
	ListRecordsByStudent(ctx context.Context, studentID int64) ([]ClearanceRecord, error)
	ListRequestsByStudent(ctx context.Context, studentID int64) ([]ClearanceRequest, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListSessions(ctx context.Context) ([]ClearanceSession, error)
	ListStaffUsers(ctx context.Context, arg ListStaffUsersParams) ([]StaffUser, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error)
	MarkNotificationRead(ctx context.Context, id int64) (Notification, error)
	UpdateClearanceItem(ctx context.Context, arg UpdateClearanceItemParams) (ClearanceItem, error)
	UpdateClearanceRecordStatus(ctx context.Context, arg UpdateClearanceRecordStatusParams) (ClearanceRecord, error)
	UpdateClearanceRequestStatus(ctx context.Context, arg UpdateClearanceRequestStatusParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (ClearanceSession, error)
	UpdateStaffUser(ctx context.Context, arg UpdateStaffUserParams) (StaffUser, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateStudentPartial(ctx context.Context, arg UpdateStudentPartialParams) (Student, error)
}

var _ Querier = (*Queries)(nil)
