// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_users.sql

package db

import (
	"context"
	"database/sql"
)

const createStaffUser = `-- name: CreateStaffUser :one
INSERT INTO staff_users (
    username, email, full_name, department_id,
    role_id, password_hash, created_at
) VALUES ($1,$2,$3,$4,$5,$6,NOW())
RETURNING id, username, email, full_name, department_id, role_id, password_hash, created_at
`

type CreateStaffUserParams struct {
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	FullName     sql.NullString `json:"full_name"`
	DepartmentID sql.NullInt64  `json:"department_id"`
	RoleID       sql.NullInt64  `json:"role_id"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error) {
	row := q.db.QueryRowContext(ctx, createStaffUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.DepartmentID,
		arg.RoleID,
		arg.PasswordHash,
	)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.DepartmentID,
		&i.RoleID,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStaffUser = `-- name: DeleteStaffUser :exec
DELETE FROM staff_users WHERE id = $1
`

func (q *Queries) DeleteStaffUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStaffUser, id)
	return err
}

const getStaffUser = `-- name: GetStaffUser :one
SELECT id, username, email, full_name, department_id, role_id, password_hash, created_at FROM staff_users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStaffUser(ctx context.Context, id int64) (StaffUser, error) {
	row := q.db.QueryRowContext(ctx, getStaffUser, id)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.DepartmentID,
		&i.RoleID,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffUserByEmail = `-- name: GetStaffUserByEmail :one
SELECT id, username, email, full_name, department_id, role_id, password_hash, created_at FROM staff_users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetStaffUserByEmail(ctx context.Context, email sql.NullString) (StaffUser, error) {
	row := q.db.QueryRowContext(ctx, getStaffUserByEmail, email)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.DepartmentID,
		&i.RoleID,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffUserByUsername = `-- name: GetStaffUserByUsername :one
SELECT id, username, email, full_name, department_id, role_id, password_hash, created_at FROM staff_users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetStaffUserByUsername(ctx context.Context, username sql.NullString) (StaffUser, error) {
	row := q.db.QueryRowContext(ctx, getStaffUserByUsername, username)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.DepartmentID,
		&i.RoleID,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listStaffUsers = `-- name: ListStaffUsers :many
SELECT id, username, email, full_name, department_id, role_id, password_hash, created_at FROM staff_users ORDER BY id LIMIT $1 OFFSET $2
`

type ListStaffUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStaffUsers(ctx context.Context, arg ListStaffUsersParams) ([]StaffUser, error) {
	rows, err := q.db.QueryContext(ctx, listStaffUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaffUser{}
	for rows.Next() {
		var i StaffUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.DepartmentID,
			&i.RoleID,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaffUser = `-- name: UpdateStaffUser :one
UPDATE staff_users SET
    username = $1,
    email = $2,
    full_name = $3,
    department_id = $4,
    role_id = $5,
    password_hash = $6
WHERE id = $7
RETURNING id, username, email, full_name, department_id, role_id, password_hash, created_at
`

type UpdateStaffUserParams struct {
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	FullName     sql.NullString `json:"full_name"`
	DepartmentID sql.NullInt64  `json:"department_id"`
	RoleID       sql.NullInt64  `json:"role_id"`
	PasswordHash sql.NullString `json:"password_hash"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateStaffUser(ctx context.Context, arg UpdateStaffUserParams) (StaffUser, error) {
	row := q.db.QueryRowContext(ctx, updateStaffUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.DepartmentID,
		arg.RoleID,
		arg.PasswordHash,
		arg.ID,
	)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.DepartmentID,
		&i.RoleID,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
