// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package db

import (
	"context"
	"database/sql"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    student_number,
    first_name,
    last_name,
    email,
    phone,
    department_id,
    enrollment_year,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
RETURNING id, student_number, first_name, last_name, email, phone, department_id, enrollment_year, created_at
`

type CreateStudentParams struct {
	StudentNumber  sql.NullString `json:"student_number"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	DepartmentID   sql.NullInt64  `json:"department_id"`
	EnrollmentYear sql.NullInt32  `json:"enrollment_year"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent,
		arg.StudentNumber,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.EnrollmentYear,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, id)
	return err
}

const getStudent = `-- name: GetStudent :one
SELECT id, student_number, first_name, last_name, email, phone, department_id, enrollment_year, created_at FROM students
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByStudentNumber = `-- name: GetStudentByStudentNumber :one
SELECT id, student_number, first_name, last_name, email, phone, department_id, enrollment_year, created_at FROM students
WHERE student_number = $1 LIMIT 1
`

func (q *Queries) GetStudentByStudentNumber(ctx context.Context, studentNumber sql.NullString) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByStudentNumber, studentNumber)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.CreatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_number, first_name, last_name, email, phone, department_id, enrollment_year, created_at FROM students
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.DepartmentID,
			&i.EnrollmentYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET
    student_number = $1,
    first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    department_id = $6,
    enrollment_year = $7
WHERE id = $8
RETURNING id, student_number, first_name, last_name, email, phone, department_id, enrollment_year, created_at
`

type UpdateStudentParams struct {
	StudentNumber  sql.NullString `json:"student_number"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	DepartmentID   sql.NullInt64  `json:"department_id"`
	EnrollmentYear sql.NullInt32  `json:"enrollment_year"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudent,
		arg.StudentNumber,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.EnrollmentYear,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentID,
		&i.EnrollmentYear,
		&i.CreatedAt,
	)
	return i, err
}
